name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build --outdir dist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Capture Wheel Filename
        id: wheel_filename
        run: |
          WHEEL_FILE=$(ls dist/*.whl)
          BASENAME=$(basename "$WHEEL_FILE")
          echo "WHEEL_FILE=$WHEEL_FILE" >> $GITHUB_ENV
          echo "WHEEL_BASENAME=$BASENAME" >> $GITHUB_ENV

      - name: Upload wheel to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.WHEEL_FILE }}
          asset_name: ${{ env.WHEEL_BASENAME }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
